/* 
 * SPInAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Dejavoo.Spin.Sdk.Client.Model
{
    /// <summary>
    ///     UserInputResponseContract
    /// </summary>
    [DataContract]
    public sealed class UserInputResponseContract : IEquatable<UserInputResponseContract>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="UserInputResponseContract" /> class.
        /// </summary>
        /// <param name="inputedString">inputedString.</param>
        /// <param name="generalResponse">generalResponse.</param>
        public UserInputResponseContract(string inputedString = default, GeneralResponseContract generalResponse = default)
        {
            InputedString = inputedString;
            GeneralResponse = generalResponse;
        }

        /// <summary>
        ///     Gets or Sets InputedString
        /// </summary>
        [DataMember(Name = "InputedString", EmitDefaultValue = false)]
        public string InputedString { get; set; }

        /// <summary>
        ///     Gets or Sets GeneralResponse
        /// </summary>
        [DataMember(Name = "GeneralResponse", EmitDefaultValue = false)]
        public GeneralResponseContract GeneralResponse { get; set; }

        /// <summary>
        ///     Returns true if UserInputResponseContract instances are equal
        /// </summary>
        /// <param name="input">Instance of UserInputResponseContract to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserInputResponseContract input)
        {
            if (input == null)
                return false;

            return
                (
                    InputedString == input.InputedString ||
                    (InputedString != null &&
                     InputedString.Equals(input.InputedString))
                ) &&
                (
                    GeneralResponse == input.GeneralResponse ||
                    (GeneralResponse != null &&
                     GeneralResponse.Equals(input.GeneralResponse))
                );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserInputResponseContract {\n");
            sb.Append("  InputedString: ").Append(InputedString).Append("\n");
            sb.Append("  GeneralResponse: ").Append(GeneralResponse).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as UserInputResponseContract);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (InputedString != null)
                    hashCode = hashCode * 59 + InputedString.GetHashCode();
                if (GeneralResponse != null)
                    hashCode = hashCode * 59 + GeneralResponse.GetHashCode();
                return hashCode;
            }
        }
    }
}